name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Create Required Directories
      run: |
        mkdir -p uploads
        mkdir -p training-data/voice-samples
        
    - name: Test Application Setup
      run: |
        echo "Testing application setup"
        # Add test commands here when tests are available
    
    - name: List Build Artifacts
      run: ls -la dist/